# nu-cyjournal — git-style plumbing for Bostrom-Journal particles.
#
# A particle is the IPFS CID v0 of a markdown file's exact bytes. This module
# parses BostromJournal001.md into sections, rebuilds the particle for each
# section edited on this branch (vs `main`), and rewires its `[~]` link to the
# new CID. Composable plumbing: parse -> build body -> hash -> place/rewire.

export use cid-v0.nu

# Parse journal markdown into sections.
#
# A section starts at a heading line carrying a `[~](...)` marker and runs to
# (not including) the next heading of any level. The marker has two valid forms:
# `[~](particles/<cid>.md)` (existing particle) and `[~]()` (genesis — a new
# chapter with no parent yet). Headings without a `[~]` marker have no particle
# and are skipped. A marker whose link is neither empty nor a particle path is
# an authoring mistake and raises an error (fail-fast).
#
# Returns rows { cid, heading, body, line } where `cid` is the current particle
# CID from the marker (or "" for genesis), `heading` is the heading text with
# the marker suffix removed, `body` is the section text with leading/trailing
# blank lines stripped (otherwise byte-verbatim), and `line` is the heading's
# 0-based index into `$in | lines` (the rewire targets it positionally).
export def parse-sections []: string -> table {
    let lines = $in | lines
    let heading_idx = $lines | enumerate | where item =~ '^#{1,6} ' | get index
    let next_idx = $heading_idx | skip 1 | append ($lines | length)
    $heading_idx | zip $next_idx | each {|pair|
        let hi = $pair.0
        let ni = $pair.1
        let m = $lines | get $hi | parse --regex '^#{1,6} (?<heading>.*) \[~\]\((?<link>[^)]*)\)$'
        if ($m | is-empty) {
            null
        } else {
            let cid = $m.0.link | parse-marker-link
            # A heading-only section gives an empty range, which `slice` returns as [].
            let body_lines = $lines | slice ($hi + 1)..<$ni
            {cid: $cid heading: $m.0.heading body: ($body_lines | strip-blank-edges) line: $hi}
        }
    } | compact
}

# Resolve a `[~](...)` marker link to a particle CID. Empty link -> genesis "".
# A `particles/<cid>.md` path -> its CID. Anything else is an authoring mistake.
def parse-marker-link []: string -> string {
    let link = $in
    if ($link | is-empty) {
        ""
    } else {
        let m = $link | parse --regex '^particles/(?<cid>[^)]+)\.md$'
        if ($m | is-empty) {
            error make {msg: $"malformed [~] marker link: ($link) — expected empty or particles/<cid>.md"}
        }
        $m.0.cid
    }
}

# Drop leading and trailing blank lines from a list of lines, return as text.
def strip-blank-edges []: list<string> -> string {
    let lines = $in
    let nonblank = $lines | enumerate | where ($it.item | str trim) != "" | get index
    if ($nonblank | is-empty) {
        ""
    } else {
        $lines | slice ($nonblank | first)..($nonblank | last) | str join "\n"
    }
}

# Assemble a particle's exact file bytes for one section.
#
# The body is the heading normalized to a single `#` (h1) with the `[~]` marker
# removed, then the section text, then exactly one trailing newline. A
# heading-only section (empty body) yields just the `# heading` line.
#
# A genesis section (`cid == ""`) has no parent, so it carries no frontmatter at
# all — a bare body. (Rule: presence of `parent:` frontmatter <=> the particle
# has a previous version; absence <=> genesis. Bare bodies also match how the
# original cyber particles were stored.) Otherwise a `parent:` frontmatter
# carries the previous-version CID (a plain string).
export def build-particle []: record -> string {
    let sec = $in
    let head = if ($sec.cid | is-empty) { "" } else { $"---\nparent: ($sec.cid)\n---\n\n" }
    let body = if ($sec.body | is-empty) {
        $"# ($sec.heading)\n"
    } else {
        $"# ($sec.heading)\n\n($sec.body)\n"
    }
    $head + $body
}

# CID v0 of a particle's text (its exact UTF-8 bytes).
export def hash-particle []: string -> string {
    $in | into binary | cid-v0
}

# Sections whose assembled particle body differs between `ref` and the working
# tree of `file`. Sections are matched across versions by their `[~]` CID
# (stable identity), so a renamed heading on the same CID is still tracked.
#
# Genesis sections (`cid == ""`) are excluded: they are marker-driven, not
# diff-driven, and are regenerated by `regenerate` regardless of `ref`. The old
# index is built only over non-empty cids, so empty keys can't collide.
#
# Returns the current-working-tree section rows for the changed sections.
export def changed-sections [
    file: string # journal path, e.g. BostromJournal001.md
    --ref: string = "main" # git ref to diff against
]: nothing -> table {
    let old_secs = ^git show $"($ref):($file)" | parse-sections | where cid != ""
    let new_secs = open --raw $file | parse-sections
    # Index old by cid -> assembled body, so identity survives heading renames.
    let old_body = $old_secs | reduce --fold {} {|s acc| $acc | insert $s.cid ($s | build-particle) }
    $new_secs | where {|s|
        let old = $old_body | get --optional $s.cid
        $old != null and $old != ($s | build-particle)
    }
}

# Headings of a markdown text, skipping fenced code blocks.
# Returns rows {level, text, line}: heading level by `#` count, text after the
# hashes (marker included, verbatim), 0-based line index into `$in | lines`.
def parse-headings []: string -> table {
    let lines = $in | lines
    let fences = $lines | enumerate | where item =~ '^```' | get index
    $lines
    | enumerate
    | where item =~ '^#{1,6} '
    | where {|row| ($fences | where $it < $row.index | length) mod 2 == 0 }
    | each {|row|
        let m = $row.item | parse --regex '^(?<hashes>#+) (?<text>.*)$' | first
        {level: ($m.hashes | str length) text: $m.text line: $row.index}
    }
}

# Render a heading's `[~](...)` marker the way GitHub renders it: as its link
# text `~`. Rendered text is what enters the TOC entry and the anchor slug.
def render-marker []: string -> string {
    str replace --regex '\[~\]\([^)]*\)' '~'
}

# Drop the marker (with its leading space) — the bare heading title,
# for matching a heading against a `--title` argument.
def strip-marker []: string -> string {
    str replace --regex ' ?\[~\]\([^)]*\)' ''
}

# GFM anchor slug (github-slugger rules): lowercase, drop everything except
# letters, digits, `_`, `-` and spaces, then spaces -> hyphens. Numbering of
# duplicates (-1, -2, …) is the caller's job — it needs document order.
def gfm-slug []: string -> string {
    str lowercase
    | str replace --all --regex '[^\p{L}\p{N}_\- ]' ''
    | str replace --all ' ' '-'
}

# Build and place the table-of-contents chapter of a journal file.
#
# Entries are the headings that follow the TOC chapter: `###` at the top level,
# `####` nested one level; deeper headings are omitted — as in 001's original
# TOC. Anchors follow GitHub's slugger, with duplicates numbered document-wide
# in heading order (GitHub counts every heading on the page, listed or not).
# A `[~]` marker renders as `~`, so it enters both entry text and anchor —
# rerun after markers change and the anchors stay correct.
#
# An existing chapter titled `--title` is rewritten in place, its heading line
# kept byte-verbatim (the `[~]` marker survives). Otherwise the chapter is
# inserted after the first `###` section — Issue metadata; the TOC follows it.
# Returns the TOC block; --dry-run returns it without touching the file.
export def toc [
    file: string = "BostromJournal001.md" # journal to build the TOC for
    --title: string = "Table of contents" # TOC chapter heading (ru: Оглавление)
    --dry-run # return the TOC block without writing the file
]: nothing -> string {
    let text = open --raw $file | decode utf-8
    let lines = $text | split row "\n"
    let slugged = $text | parse-headings | reduce --fold {seen: {}, rows: []} {|h, acc|
        let base = $h.text | render-marker | gfm-slug
        let n = $acc.seen | get --optional $base | default 0
        {
            seen: ($acc.seen | upsert $base ($n + 1))
            rows: ($acc.rows | append ($h | insert slug (if $n == 0 { $base } else { $"($base)-($n)" })))
        }
    } | get rows
    let existing = $slugged | where {|h| ($h.text | strip-marker) == $title }
    let span = if ($existing | is-not-empty) {
        let start = $existing | first | get line
        {
            start: $start
            end: ($slugged | where line > $start | first | get line)
            heading: ($lines | get $start)
        }
    } else {
        let meta = $slugged | where level == 3 | first
        let at = $slugged | where line > $meta.line | first | get line
        {start: $at end: $at heading: $"### ($title)"}
    }
    let bullets = $slugged | where line >= $span.end | where level in [3 4] | each {|h|
        let indent = if $h.level == 3 { "" } else { "  " }
        $"($indent)- [($h.text | render-marker)]\(#($h.slug)\)"
    }
    let block = [$span.heading ""] | append $bullets | append ""
    if not $dry_run {
        ($lines | slice 0..<$span.start)
        | append $block
        | append ($lines | slice $span.end..)
        | str join "\n"
        | save --force --raw $file
    }
    $block | str join "\n"
}

# Regenerate particles for the journal's sections and rewire their `[~]` markers.
#
# Two disjoint sets are processed: genesis sections (`[~]()`, marker-driven,
# regenerated regardless of `ref`) and edited sections (existing particles whose
# body changed vs `ref`). For each: build the new particle, hash it to its CID,
# write `particles/<new-cid>.md`, and fill the marker to the new CID.
#
# Rewire is positional, by heading line index — multiple `[~]()` markers are
# byte-identical, so a document-wide `str replace` would mis-target. The file is
# read losslessly and the marker on each section's own line is rewritten.
# Returns rows { heading, old_cid, new_cid }; genesis rows use "" as old_cid.
export def regenerate [
    file: string = "BostromJournal001.md" # journal to regenerate
    --ref: string = "main" # git ref to diff against
    --particles-dir: string = "particles" # where particle files live
    --dry-run # report what would change without writing
]: nothing -> table {
    let genesis = open --raw $file | parse-sections | where cid == ""
    let changed = changed-sections $file --ref $ref
    let plan = $genesis | append $changed | each {|s|
            let bytes = $s | build-particle
            {heading: $s.heading old_cid: $s.cid new_cid: ($bytes | hash-particle) line: $s.line bytes: $bytes}
        }
    # Why: an empty plan is a no-op — skip the write entirely so a no-op
    # regenerate touches nothing (no rewritten file, no mtime change).
    if not $dry_run and ($plan | is-not-empty) {
        # Write particle files.
        $plan | each {|p| $p.bytes | save --force --raw $"($particles_dir)/($p.new_cid).md" }
        # Rewire markers positionally: rewrite the marker on each section's line.
        # Decode to a string first: `split row "\n"` on raw bytes drops the
        # trailing empty element, losing the file's final newline; on a string it
        # round-trips exactly (so does join). Line indices from `lines` agree.
        let lines = open --raw $file | decode utf-8 | split row "\n"
        let updated = $plan | reduce --fold $lines {|p acc|
                $acc | update $p.line { str replace --regex '\[~\]\([^)]*\)' $"[~]\(($particles_dir)/($p.new_cid).md\)" }
            }
        $updated | str join "\n" | save --force --raw $file
    }
    $plan | select heading old_cid new_cid
}
